services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=artgallery'
      - 'POSTGRES_PASSWORD=deninochsteregyt'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
