version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=artgallery'
      - 'POSTGRES_PASSWORD=1'
      - 'POSTGRES_USER=daria'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  artgallery:
    build: .
    container_name: artgallery
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
